/**
 * The day's painting, and how to prove where it came from.
 *
 * GENERATED by `.ai/tools/fetch_scrolls.py` on 2026-10-01 - do not hand-edit.
 * The generator measured the widths and heights after downscaling, and a
 * hand-typed intrinsic size is a size that is eventually wrong invisibly: the
 * layout reserves the wrong box, the image lands in it, and nothing says so.
 *
 * Thirty-one paintings, one per day of the month, chosen from the Cleveland
 * Museum of Art's CC0 holdings. All thirty-one are public domain in the
 * museum's own sense - `images.web.copyright` is empty and the API's `cc0=1`
 * filter returned them - and the underlying paintings are four to seven
 * centuries old, so the copyright in the photographs expired long before the
 * camera did.
 *
 * See `PROVENANCE.md` beside this file for the per-painting receipt. This file
 * carries only what the interface actually renders.
 *
 * The credited name is the museum's, romanised. It is stored rather than
 * looked up at runtime because a launch screen must not depend on the network,
 * and because a credit that can fail to render is not a credit.
 */

export interface Scroll {
  /** 1-31. `null` when the date has no day in it. */
  readonly day: number
  /** Intrinsic width, measured. */
  readonly width: number
  /** Intrinsic height, measured. */
  readonly height: number
  readonly artist: string
  readonly title: string
  readonly date: string
  /** Where it is held. Rendered in the credit line. */
  readonly museum: string
  readonly accession: string
  /** The museum's page for this object. */
  readonly source: string
}

export const SCROLL_MUSEUM = 'The Cleveland Museum of Art'

export const SCROLLS: readonly Scroll[] = [
  {
    day: 1,
    width: 1133,
    height: 893,
    artist: 'Zha Shibiao (Chinese, 1615–1698)',
    title: 'Landscape Album in Various Styles: The Stream of Wuling',
    date: '1684',
    museum: 'The Cleveland Museum of Art',
    accession: '1955.37.4',
    source: 'https://clevelandart.org/art/1955.37.4',
  },
  {
    day: 2,
    width: 900,
    height: 674,
    artist: 'Zha Shibiao (Chinese, 1615–1698)',
    title: 'Landscape Album in Various Styles: Traveling in Autumn Mountains',
    date: '1684',
    museum: 'The Cleveland Museum of Art',
    accession: '1955.37.6',
    source: 'https://clevelandart.org/art/1955.37.6',
  },
  {
    day: 3,
    width: 900,
    height: 679,
    artist: 'Zha Shibiao (Chinese, 1615–1698)',
    title: 'Landscape Album in Various Styles: Pleasure in a Mountain Brook',
    date: '1684',
    museum: 'The Cleveland Museum of Art',
    accession: '1955.37.9',
    source: 'https://clevelandart.org/art/1955.37.9',
  },
  {
    day: 4,
    width: 900,
    height: 704,
    artist: 'Zha Shibiao (Chinese, 1615–1698)',
    title: 'Landscape Album in Various Styles: Spring Plowing',
    date: '1684',
    museum: 'The Cleveland Museum of Art',
    accession: '1955.37.2',
    source: 'https://clevelandart.org/art/1955.37.2',
  },
  {
    day: 5,
    width: 1158,
    height: 893,
    artist: 'Zha Shibiao (Chinese, 1615–1698)',
    title: 'Landscape Album in Various Styles: Landscape after Mi Fei',
    date: '1684',
    museum: 'The Cleveland Museum of Art',
    accession: '1955.37.8',
    source: 'https://clevelandart.org/art/1955.37.8',
  },
  {
    day: 6,
    width: 1263,
    height: 835,
    artist: 'Mei Qing (Chinese, 1623–1697)',
    title: 'Landscapes in Various Styles after Old Masters',
    date: '1690',
    museum: 'The Cleveland Museum of Art',
    accession: '1962.157.1',
    source: 'https://clevelandart.org/art/1962.157.1',
  },
  {
    day: 7,
    width: 1263,
    height: 830,
    artist: 'Mei Qing (Chinese, 1623–1697)',
    title: 'Landscapes in Various Styles after Old Masters',
    date: '1690',
    museum: 'The Cleveland Museum of Art',
    accession: '1962.157.10',
    source: 'https://clevelandart.org/art/1962.157.10',
  },
  {
    day: 8,
    width: 378,
    height: 900,
    artist: 'Ikkyū Sōjun (Japanese, 1394–1481)',
    title: 'Listening to the Wind in the Pines',
    date: '1400s',
    museum: 'The Cleveland Museum of Art',
    accession: '1985.89',
    source: 'https://clevelandart.org/art/1985.89',
  },
  {
    day: 9,
    width: 1263,
    height: 838,
    artist: 'Mei Qing (Chinese, 1623–1697)',
    title: 'Landscapes in Various Styles after Old Masters',
    date: '1690',
    museum: 'The Cleveland Museum of Art',
    accession: '1962.157.8',
    source: 'https://clevelandart.org/art/1962.157.8',
  },
  {
    day: 10,
    width: 572,
    height: 893,
    artist: 'Min Zhen (Chinese, 1730–after 1788)',
    title: 'Cat and Butterfly',
    date: '1788',
    museum: 'The Cleveland Museum of Art',
    accession: '1985.71.5',
    source: 'https://clevelandart.org/art/1985.71.5',
  },
  {
    day: 11,
    width: 1209,
    height: 893,
    artist: 'Shen Zhou (Chinese, 1427–1509)',
    title: 'The Thousand Acres of Clouds, from Twelve Views of Tiger Hill, Suzhou',
    date: 'after 1490',
    museum: 'The Cleveland Museum of Art',
    accession: '1964.371.9',
    source: 'https://clevelandart.org/art/1964.371.9',
  },
  {
    day: 12,
    width: 1136,
    height: 893,
    artist: 'Shen Zhou (Chinese, 1427–1509)',
    title: 'Distant View of Tiger Hill from the Canal Mooring, from Twelve Views of Tiger Hill, Suzhou',
    date: 'after 1490',
    museum: 'The Cleveland Museum of Art',
    accession: '1964.371.1',
    source: 'https://clevelandart.org/art/1964.371.1',
  },
  {
    day: 13,
    width: 321,
    height: 900,
    artist: 'Narihide (Japanese, active 1500s)',
    title: 'Landscape',
    date: '1500s',
    museum: 'The Cleveland Museum of Art',
    accession: '2015.470',
    source: 'https://clevelandart.org/art/2015.470',
  },
  {
    day: 14,
    width: 500,
    height: 893,
    artist: 'Wang Yuanqi (Chinese, 1642–1715)',
    title: 'Landscape after Ni Zan',
    date: '1707',
    museum: 'The Cleveland Museum of Art',
    accession: '1954.583',
    source: 'https://clevelandart.org/art/1954.583',
  },
  {
    day: 15,
    width: 451,
    height: 893,
    artist: 'Wang Hui (Chinese, 1632–1717)',
    title: 'Tall Bamboo and Distant Mountains, after Wang Meng',
    date: '1694',
    museum: 'The Cleveland Museum of Art',
    accession: '1953.629',
    source: 'https://clevelandart.org/art/1953.629',
  },
  {
    day: 16,
    width: 364,
    height: 893,
    artist: 'Wen Zhengming (Chinese, 1470–1559)',
    title: 'Old Trees by a Wintry Brook',
    date: '1551',
    museum: 'The Cleveland Museum of Art',
    accession: '1997.102',
    source: 'https://clevelandart.org/art/1997.102',
  },
  {
    day: 17,
    width: 900,
    height: 560,
    artist: 'Tani Bunchō (Japanese, 1763–1841)',
    title: 'Returning Sails off a Distant Shores, from Eight Views of Xiao-Xiang',
    date: '1788',
    museum: 'The Cleveland Museum of Art',
    accession: '1980.188.3',
    source: 'https://clevelandart.org/art/1980.188.3',
  },
  {
    day: 18,
    width: 386,
    height: 893,
    artist: 'Bada Shanren (Chinese, 1626–1705)',
    title: 'Landscape after Guo Zhongshu',
    date: 'c. 1680–1705',
    museum: 'The Cleveland Museum of Art',
    accession: '1955.36',
    source: 'https://clevelandart.org/art/1955.36',
  },
  {
    day: 19,
    width: 900,
    height: 557,
    artist: 'Tani Bunchō (Japanese, 1763–1841)',
    title: 'Wild Geese Descending on a Sandbar, from Eight Views of Xiao-Xiang',
    date: '1788',
    museum: 'The Cleveland Museum of Art',
    accession: '1980.188.4',
    source: 'https://clevelandart.org/art/1980.188.4',
  },
  {
    day: 20,
    width: 447,
    height: 893,
    artist: '(无款)',
    title: 'Landscape',
    date: '1800s',
    museum: 'The Cleveland Museum of Art',
    accession: '1915.217',
    source: 'https://clevelandart.org/art/1915.217',
  },
  {
    day: 21,
    width: 675,
    height: 893,
    artist: 'Xiao Yuncong (Chinese, 1596–1673)',
    title: 'Album of Seasonal Landscapes, Leaf D (previous leaf 2)',
    date: '1668',
    museum: 'The Cleveland Museum of Art',
    accession: '1955.302.2',
    source: 'https://clevelandart.org/art/1955.302.2',
  },
  {
    day: 22,
    width: 673,
    height: 893,
    artist: 'Xiao Yuncong (Chinese, 1596–1673)',
    title: 'Album of Seasonal Landscapes, Leaf E (previous leaf 3)',
    date: '1668',
    museum: 'The Cleveland Museum of Art',
    accession: '1955.302.3',
    source: 'https://clevelandart.org/art/1955.302.3',
  },
  {
    day: 23,
    width: 674,
    height: 893,
    artist: 'Xiao Yuncong (Chinese, 1596–1673)',
    title: 'Album of Seasonal Landscapes, Leaf A (previous leaf 4)',
    date: '1668',
    museum: 'The Cleveland Museum of Art',
    accession: '1955.302.4',
    source: 'https://clevelandart.org/art/1955.302.4',
  },
  {
    day: 24,
    width: 1263,
    height: 596,
    artist: 'Kuncan (Chinese, 1612–c. 1673)',
    title: 'Spring Landscape',
    date: '1666',
    museum: 'The Cleveland Museum of Art',
    accession: '1966.367',
    source: 'https://clevelandart.org/art/1966.367',
  },
  {
    day: 25,
    width: 460,
    height: 893,
    artist: 'Li Shizhuo (Chinese, c. 1690–1770)',
    title: 'Landscape after Jing Hao and Guan Tong',
    date: '1700s',
    museum: 'The Cleveland Museum of Art',
    accession: '1952.588',
    source: 'https://clevelandart.org/art/1952.588',
  },
  {
    day: 26,
    width: 362,
    height: 900,
    artist: 'Yosa Buson (Japanese, 1716–1783)',
    title: 'Snow Landscape',
    date: 'mid-1770s',
    museum: 'The Cleveland Museum of Art',
    accession: '1997.111',
    source: 'https://clevelandart.org/art/1997.111',
  },
  {
    day: 27,
    width: 1263,
    height: 561,
    artist: 'Ike Taiga (Japanese, 1723–1776)',
    title: 'West Lake',
    date: 'mid-1700s',
    museum: 'The Cleveland Museum of Art',
    accession: '1970.69',
    source: 'https://clevelandart.org/art/1970.69',
  },
  {
    day: 28,
    width: 523,
    height: 893,
    artist: 'Xu Ben (Chinese, 1335–1380)',
    title: 'Streams and Mountains',
    date: '1372',
    museum: 'The Cleveland Museum of Art',
    accession: '1997.96',
    source: 'https://clevelandart.org/art/1997.96',
  },
  {
    day: 29,
    width: 305,
    height: 893,
    artist: 'Dong Qichang (Chinese, 1555–1636)',
    title: 'Mt. Qingbian',
    date: '1617',
    museum: 'The Cleveland Museum of Art',
    accession: '1980.10',
    source: 'https://clevelandart.org/art/1980.10',
  },
  {
    day: 30,
    width: 395,
    height: 900,
    artist: 'Wen Zhengming (Chinese, 1470–1559)',
    title: 'Playing the Qin in a Secluded Valley',
    date: '1548',
    museum: 'The Cleveland Museum of Art',
    accession: '1969.60',
    source: 'https://clevelandart.org/art/1969.60',
  },
  {
    day: 31,
    width: 336,
    height: 893,
    artist: 'Sesshū Tōyō (Japanese, 1420–1506)',
    title: 'Haboku, Splashed Ink Landscape',
    date: '1400s–early 1500s',
    museum: 'The Cleveland Museum of Art',
    accession: '1955.43',
    source: 'https://clevelandart.org/art/1955.43',
  },
]

/**
 * The image files, resolved by Vite.
 *
 * `?url` rather than a plain import so each entry is a URL string and not a
 * module object, and `eager` because the launch screen needs the URL
 * synchronously on the first paint - a lazy glob would resolve after the
 * screen has already decided it has no painting, which is a blank launch for
 * one frame on every cold start.
 *
 * The images themselves are *not* bundled into the JavaScript: they are emitted
 * as separate files and fetched only when an `<img>` asks for one, so a reader
 * who dismisses the launch screen never downloads any of them.
 */
const FILES = import.meta.glob('./*.jpg', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>

function urlFor(day: number): string {
  const key = `./day-${String(day).padStart(2, '0')}.jpg`
  const found = FILES[key]
  if (found === undefined) {
    throw new Error(`no artwork for day ${day}; the manifest and the folder disagree`)
  }
  return found
}

/**
 * Which painting a date gets.
 *
 * **The day of the month, not a hash of the date.** A month has thirty or
 * thirty-one days, the artwork has thirty-one sheets, and the day of the month
 * is the one function from a date to a painting that a reader can predict and
 * therefore check. A hash would be stable but arbitrary: it would also give the
 * same picture to the 3rd of April and the 3rd of May and no way to say why.
 *
 * February has no 30th or 31st, so `day` is clamped into the range that
 * exists rather than returning nothing - the alternative is a launch screen with
 * a hole in it for five weeks a year.
 */
export function scrollFor(date: Date): Scroll {
  const raw = date.getDate()
  const day = Math.min(SCROLLS.length, Math.max(1, raw))
  const found = SCROLLS[day - 1]
  if (found === undefined) {
    throw new Error(`SCROLLS has no entry for day ${day}`)
  }
  return found
}

/** The URL for the painting this date gets. */
export function scrollUrlFor(date: Date): string {
  return urlFor(scrollFor(date).day)
}

